### ISSUE TITLE
A doubt

### ISSUE THREAD

**Issue by AnaxyJod** [KhanhNguyen9872/dump_marshal_py#3]
With this tool, it can decode this type of enc ?
 _ = lambda __: __import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
I tried but it doesn't seems to be working

**Comment by KhanhNguyen9872** [comment]
> With this tool, it can decode this type of enc ? _ = lambda **: import('zlib').decompress(import('base64').b64decode(**[::-1])) I tried but it doesn't seems to be working

zlib just print it to see result, this tool only work when code use marshal library
example:
```python3
def look(arg):
    print(arg)
    return arg
_ = lambda : look(import('zlib').decompress(import('base64').b64decode([::-1])))
exec((_)(b'code'))
```

**Comment by AnaxyJod** [comment]
Alright, thanks ❤️

**Comment by AnaxyJod** [comment]
Alright, thanks for sharing this ❤️
