### ISSUE TITLE
idk

### ISSUE THREAD

**Issue by seized0** [KhanhNguyen9872/dump_marshal_py#4]
dumping....
dump count -> 0 completed (marshal)!
ERROR:root:Traceback (most recent call last):
  File "C:\Users\nadek\Desktop\dump_marshal.py", line 180, in <module>
    exec('import marshal;exec(marshal.loads(' + str(__import__('marshal').dumps(compile(marshal, '<KhanhNguyen9872>', 'exec'))) + "), globals())",globals())
  File "<string>", line 1, in <module>
  File "<KhanhNguyen9872>", line 26, in <module>
  File "<KhanhNguyen9872>", line 30, in loads
ValueError: bad marshal data (unknown type code)
![image_2024-09-07_171311172](https://github.com/user-attachments/assets/c2c7ef5f-c8e0-4be3-9a0a-6c5a9caf6182)

**Comment by KhanhNguyen9872** [comment]
> dumping.... dump count -> 0 completed (marshal)! ERROR:root:Traceback (most recent call last): File "C:\Users\nadek\Desktop\dump_marshal.py", line 180, in exec('import marshal;exec(marshal.loads(' + str(**import**('marshal').dumps(compile(marshal, '', 'exec'))) + "), globals())",globals()) File "", line 1, in File "", line 26, in File "", line 30, in loads ValueError: bad marshal data (unknown type code) ![image_2024-09-07_171311172](https://private-user-images.githubusercontent.com/176520464/365378244-c2c7ef5f-c8e0-4be3-9a0a-6c5a9caf6182.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3NjM5NTYsIm5iZiI6MTcyNTc2MzY1NiwicGF0aCI6Ii8xNzY1MjA0NjQvMzY1Mzc4MjQ0LWMyYzdlZjVmLWM4ZTAtNGJlMy05YTBhLTZjNWE5Y2FmNjE4Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOFQwMjQ3MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNmViNzU2NGI1MzU3ZGViMzczMGJkM2IwOGUzNDQ1OWY5MDNlYmVmNmZhMzg3N2IxM2RhMWYzODE4OTUxZjQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nm6QN6c6gKOhXsb9_9K8EALD5QvkdtZyEFWxPzF97wk)

please using another version of python, this obfuscate file isn't work in current python

**Comment by KhanhNguyen9872** [comment]
you can install all version of python (3.8 3.9 3.10 3.11 3.12 3.13) and find what version can run obfuscate file
(ex: if marshal compiled in 3.11, you can only run it in 3.11, not 3.10, 3.9,....)
